REM Settings for GA Vizlab
REM Ole Nielsen, 8 January 2008

doskey
PATH %PATH%;c:\program files\anuga_viewer
set OSG_EYE_SEPARATION=.05
set OSG_SCREEN_DISTANCE=4.0
set OSG_SCREEN_HEIGHT=2.5
set OSG_SCREEN_WIDTH=6.0
set OSG_SPLIT_STEREO_HORIZONTAL_SEPARATION=0
set OSG_STEREO_MODE=QUAD_BUFFER
